# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-31 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='party',
            name='invitation_sent',
        ),
        migrations.RemoveField(
            model_name='party',
            name='is_invited',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_opened',
        ),
        migrations.RemoveField(
            model_name='party',
            name='save_the_date_sent',
        ),
        migrations.AddField(
            model_name='party',
            name='plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
