# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_auto_20180331_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='plus_one_is_attending',
            field=models.NullBooleanField(default=None),
        ),
    ]
