# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_party_plus_one_is_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
