# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_party_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='diet_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='plus_one_diet_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='plus_one_meal',
            field=models.CharField(blank=True, choices=[('chicken', 'chicken'), ('pork', 'pork'), ('neither', 'neither')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='meal',
            field=models.CharField(blank=True, choices=[('chicken', 'chicken'), ('pork', 'pork'), ('neither', 'neither')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('Wedding Party', 'Wedding Party'), ('Matt - Family', 'Matt - Family'), ('Matt - Friends', 'Matt - Friends'), ('Megan - Family', 'Megan - Family'), ('Megan - Friends', 'Megan - Friends'), ('Mutual Friends', 'Mutual Friends')], max_length=10),
        ),
    ]
