# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_auto_20180417_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('Wedding Party', 'Wedding Party'), ('Matt - Family', 'Matt - Family'), ('Matt - Friends', 'Matt - Friends'), ('Megan - Family', 'Megan - Family'), ('Megan - Friends', 'Megan - Friends'), ('Mutual Friends', 'Mutual Friends')], max_length=100),
        ),
    ]
